language: java
sudo: false
cache:
  directories:
    - $HOME/.m2

env:
  - JDK=oraclejdk8
dist: trusty
before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
before_script:
  - jdk_switcher use $JDK

script:
  - mvn clean verify --batch-mode --errors --fail-at-end --show-version

deploy:
  provider: script
  script: "mvn deploy -P gpg"
  skip_cleanup: true
  on:
      # Set `tag: true` so that the deployment is triggered only when a tagged commit is pushed
    tags: true
