language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
env:
  - JDK=oraclejdk8
dist: trusty
before_script:
  - jdk_switcher use $JDK

install: mvn clean verify -Dgpg.skip

# TODO(weiguo) not tested yet
deploy:
  provider: script
  script: "mvn --settings .travis/settings.xml deploy -P gpg"
  skip_cleanup: true
  on:
    tags: true
