language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
env:
  - JDK=oraclejdk8
dist: trusty
before_script:
  - jdk_switcher use $JDK

# install: mvn clean verify -Dgpg.skip
install: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -P gpg

# TODO(weiguo) not tested yet
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -P gpg"
  skip_cleanup: true
  on:
      # Set `tag: true` so that the deployment is triggered only when a tagged commit is pushed
    tags: true
